### ISSUE TITLE
插件编码不是UTF-8即改了js编码问题

### ISSUE THREAD

**Issue by YoumiHa** [acm233/TMEssential-Docs#2]
![image](https://github.com/acm233/TMEssential-Docs/assets/140812890/af3ca454-8014-4f69-b8ab-dbe85896c55d)
插件编码不是UTF-8即改了js编码问题

**Comment by Singl-Daemon** [comment]
json也有编码问题
这个简单，强调一遍用记事本的都是啥比就行了

**Comment by YoumiHa** [comment]
> json也有编码问题 这个简单，强调一遍用记事本的都是啥比就行了

给我点star

**Comment by Singl-Daemon** [comment]
> > json也有编码问题 这个简单，强调一遍用记事本的都是啥比就行了
> 
> 给我点star

来点pr吧，我要写不动了
