### ISSUE TITLE
没有加载js插件问题

### ISSUE THREAD

**Issue by YoumiHa** [acm233/TMEssential-Docs#3]
![image](https://github.com/acm233/TMEssential-Docs/assets/140812890/d733185f-32a1-4d5f-99ff-389e183e305a)
没有加载js插件问题,你把脚本引擎删了加个鸡儿

**Comment by Singl-Daemon** [comment]
逆天

**Comment by YoumiHa** [comment]
> 逆天

给我点star

**Comment by Singl-Daemon** [comment]
> > 逆天
> 
> 给我点star

prpr
给我pr（cry
